apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-art-explainer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-art-explainer
    app.kubernetes.io/part-of: kserve-art-explainer
  name: kserve-art-explainer
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-art-explainer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-art-explainer
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-art-explainer/kserve-art-explainer@sha256:7aaa0216a25733c73d4a93cac75e51f142e3d230bdac7875e64f92eac166ec79
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
