apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-art-explainer
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-art-explainer/kserve-art-explainer@sha256:7aaa0216a25733c73d4a93cac75e51f142e3d230bdac7875e64f92eac166ec79
        name: container-image
        resources: {}
status: {}
